# Generated by Django 5.0.4 on 2024-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_hotel_image_alter_staff_hotel_alter_staff_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotels'),
        ),
    ]
