# Generated by Django 5.0.4 on 2024-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotels_profile_pic'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.CharField(max_length=10),
        ),
    ]
