# Generated by Django 5.0.4 on 2024-05-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_hotel_image_alter_hotel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='hotels_sample_pics'),
        ),
    ]
