# Generated by Django 5.0.4 on 2024-05-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_hotel_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='sample',
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.FileField(upload_to='hotels_sample_pics')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_hotel', to='account.hotel')),
            ],
            options={
                'verbose_name': 'Sample Image',
                'verbose_name_plural': 'Sample Images',
                'ordering': ['hotel'],
            },
        ),
    ]
